name: Deltago
favicon: null
layout_spectrum: 0.9530964698642492
typography_spectrum: 0.5018350370228291
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a6caf0'
    - '#6666ff'
    - '#d8e7f8'
    - '#9595ff'
  brandStrength: 0.27613032585941255
  lightness: 0.6366069556679577
  saturation: 0.9141070325858891
  rhythmicContrast: 0.2722464916296303
purpose: []
