typography_spectrum: 0.24951
color:
  brandColors:
    - '#ffffff'
    - '#a6caf0'
    - '#6666ff'
    - '#d8e7f8'
    - '#9595ff'
  brandStrength: 0.1875
  lightness: 0.875
  saturation: 0.9141070325858891
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.91487
analytics:
  google: null
  facebook: null
  twitter: null
name: For Business Athletes
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: More...
    url: 'http://www.deltago.de'
    type: external
favicon: null
title: Deltago
description: Change leadership
purpose: []
